import { Button, Slider, VerticalBox, ScrollView, SpinBox, Spinner, TabWidget } from "std-widgets.slint";
import { LevelMeter } from "../slintcomponents/lib.slint";

// Levelmeter info
export struct TChannelMeter {
    levels: [float],
    peak_flag: [bool],
}

// Channel info
export struct TChannel {
    gain: int,
    mute: bool,
    dev_id: int,
    meter: TChannelMeter,
}

// Meeting member info
export struct TMemberInfo {
    site: int,
    name: string,
    avatar: image,
    description: string,
}

// Meeting member instance
export struct TMember  {
    info: TMemberInfo,
    channel: TChannel,
}

// Connect state
export enum TSelfConnectState  {
  disconnected,
  connecting,
  connected,
}

// Work mode
export enum TSelfMode {
  master,
  voicer,
}

// Self plane info
export struct TSelfPlane {
    info: TMemberInfo,
    mode: TSelfMode,
    channel_master: TMember,
    channel_voice: TChannel,
    channel_devout: TChannel,
    connect_state: TSelfConnectState,
}

// A avatar button
component AvatarButton inherits Rectangle {
    in property <image> avatar_image : @image-url("./resources/icon-default-user.png");
    callback clicked();
    width: 44px;
    height: 44px;
    border-width: 2px;
    border-color: #888;
    border-radius: 22px;
    clip: true;
    Image {
        source: avatar_image;
        width: parent.width;
        height: parent.height;
    }
    TouchArea {
      clicked => {
          root.clicked();
      }
    }
}

// A customizable color button
component ColorButton {
  in property <string> text : "Button";
  in property <length> border-radius : 4px;
  in property <length> border-width : 2px;
  in property <color> border-color : #444;
  in property <color> text-color : #aaa;
  in property <color> background-color : #444;
  in property <color> hover-text-color : #fff;
  in property <color> hover-background-color : #666;
  in property <color> hover-border-color : #333;

  callback clicked();
  private property <bool> is_hovered : false;

  width: 100px;
  height: 30px;
  Rectangle {
    border-color: root.is_hovered ? root.hover-border-color : root.border-color;
    border-width: 2px;
    border-radius: 4px;
    background: root.is_hovered ? root.hover-background-color : root.background-color;
    Text {
        x: parent.border-width;
        y: parent.border-width;
        text: root.text;
        horizontal-alignment: center;
        vertical-alignment: center;
        width: parent.width - parent.border-width * 2;
        height: parent.height - parent.border-width * 2;
        color: root.is_hovered ? root.hover-text-color : root.text-color;
    }
    TouchArea {
      moved() => {
          root.is_hovered = self.has-hover;
      }
      clicked => {
        root.clicked();
      }
    } 
  }
}

component LocalChannelCtrl inherits Rectangle {
    
}

component RemoteChannelCtrl inherits Rectangle {

}

//
export component AppSuf inherits Rectangle {
  in property <TSelfPlane> self_plane : {
    info: {
      site: -1,
      name: "New Moniters Meeting",
      avatar: @image-url("./resources/icon-default-user.png"),
      description: "Meeting description",
    },
    mode: TSelfMode.master,
    channel_master: {
      info:{
        site: -1,
        name: "New Moniters Meeting",
        avatar: @image-url("./resources/icon-default-user.png"),
        description: "Meeting description",
      },
      channel: {
        gain: 100,
        mute: false,
        dev_id: 0,
        meter: {
          levels: [0.0, -10.0],
          peak_flag: [true, false],
        },
      },
    },
    channel_voice: {
      gain: 50,
      mute: false,
      dev_id: 1,
      meter: {
        levels: [-50.0, -50.0],
        peak_flag: [false, false],
      },
    },
    channel_devout: {
      gain: 50,
      mute: false,
      dev_id: 2,
      meter: {
        levels: [-20.0, -30.0],
        peak_flag: [false, false],
      },
    },
    connect_state: TSelfConnectState.disconnected,
  };
  in property <[TMember]> members : [{
      info:{
        site: 1,
        name: "Remote User A",
        avatar: @image-url("./resources/icon-default-user.png"),
        description: "Remote User A Description",
      },
      channel: {
        gain: 80,
        mute: false,
        dev_id: 3,
        meter: {
          levels: [-5.0, -15.0],
          peak_flag: [true, false],
        },
      },
    },
    {
      info:{
        site: 2,
        name: "Remote User B",
        avatar: @image-url("./resources/icon-default-user.png"),
        description: "Remote User B Description",
      },
      channel: {
        gain: 60,
        mute: false,
        dev_id: 4,
        meter: {
          levels: [-30.0, -40.0],
          peak_flag: [false, false],
        },
      },
  }];
  in property <[string]> inputdevs : ["no device", "Microphone 1", "Microphone 2"];
  in property <[string]> outputdevs : ["no device", "Speaker 1", "Speaker 2"];

  
  // Body aria
  Rectangle {
    VerticalLayout {
      // Self Plane
      VerticalLayout {
        min-height: 300px;
        min-width: 300px;
        // Header aria (login, connect status and so on)
        Rectangle {
          height: 40px;
          AvatarButton {
            x: 15px;
            y: 6px;
            avatar_image: self_plane.info.avatar;
            width: 34px;
            height: 34px;
            border-radius: 16px;
            border-color: #888;
            clicked => {
              // Handle avatar click
            }
          }
          Rectangle {
            x: 52px;
            y: 10px;
            clip: true;
            width: parent.width - 182px;
            Text {
              font-size: 14px;
              font-family: "Sans Serif";
              text: self_plane.info.name;
              color: #aaa;
              states [
                  nodesc when self_plane.info.description == "" :{
                    y: 5px;
                  }
                  desc when self_plane.info.description != "" :{
                    y: 0px;
                  }
              ]
              x: 0px;
            }
            if self_plane.info.description != "": Text {
                font-size: 11px;
                font-family: "Sans Serif";
                text: self_plane.info.description;
                color: #666;
                x: 0px;
                y: 17px;
              }
          }
          // show connect button when disconnected
          if (self_plane.connect_state == TSelfConnectState.disconnected): ColorButton {
              text: "Connect";
              width: 90px;
              height: 26px;
              x: parent.width - 100px;
              y: 10px;
              text-color: #fff;
              background-color: #50A070;
              hover-background-color: #408060;
              clicked => {}
            }
          // show connecting status when connecting
          if (self_plane.connect_state == TSelfConnectState.connecting): Rectangle {
              x: parent.width - 130px;
              y: 10px;
              width: 130px;
              height: 30px;
              Text {
                text: "Connecting...";
                font-size: 12px;
                font-family: "Sans Serif";
                horizontal-alignment: right;
                width: 80px;
                x: 0px;
              }
              Spinner {
                x: 90px;
                y: 0px;
                width: 30px;
                height: 30px;
                indeterminate: false;
              }
            }
          // show disconnect button when connected
          if (self_plane.connect_state == TSelfConnectState.connected): ColorButton {
              text: "Disconnect";
              width: 90px;
              height: 26px;
              x: parent.width - 100px;
              y: 10px;
              text-color: #fff;
              background-color: #A05050;
              hover-background-color: #806060;
              clicked => {}
          }
        }
        // Control aria (mode switch, devices select and so on)
        Rectangle {
        }
      }
      // Members List
      ScrollView {
        GridLayout {}
      }
    }
  }
  // Footer aria (status, hints and so on)
  Rectangle {
  }
}

export component MainWindow inherits Window {
    in property <[TMember]> members;
    callback update_ctrl(string, int);
    callback add_member();
    callback close();
    preferred-width: 500px;
    preferred-height: 300px;
    min-width: 300px;
    min-height:200px;
    MenuBar {
        Menu {
            title: "Operations";
            MenuItem {
                title: "Config";
            }
            MenuSeparator {}
            MenuItem {
                title: "Exit";
                activated => {
                    root.close();
                }
            }
        }
        Menu {
            title: "Help";
            MenuItem {
                title: "About";
            }
        }
    }
    VerticalBox {
        Text {
            text: "Test UI";
        }
        VerticalBox {
          for m in members : VerticalBox {
            Text {
              text: m.info.name;
            }
            Text {
              text: m.info.description;
            }
            Slider {
              value: m.channel.gain;
              changed(value) => {
                update_ctrl(m.info.name, value);
              }
            }
            LevelMeter {
              height: 30px;
              levels: [0.0, -10.0];
              orientation: horizontal;
            }
          }
        }
        Button {
            text: "Add Member";
            clicked => {
                root.add_member();
            }
        }
    }
}
